---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
    set -e
    yamllint .
    ansible-lint .
platforms:
  - name: gentoo-amd64
    image: "fgierlinger/gentoo-amd64:latest"
    command: ""
    tmpfs:
        - /run
        - /tmp
    volumes:
        - /dev:/dev:ro
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
